apiVersion: v1
kind: Service
metadata:
  name: document-service
  labels:
    app: document-service
spec:
  selector:
    app: document-service #send traffic to pods that have label app=document-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
