name: CI

# run when main is updated
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write # write for packages to be able to push images to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # pull repo code into the VM
      - name: Checkout
        uses: actions/checkout@v4

      # install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install dependencies from requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # sanity check : python files compile    
      - name: Basic check (compile)
        run: python -m compileall app
      
      # login to GHCR, Token automatically created for each worflow run
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build images using Dockerfile and push to GHCR
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/document-service:latest
            ghcr.io/${{ github.repository_owner }}/document-service:${{ github.sha }}
